name: Kotlin Multiplatform Tests
on: [push]

env:
  MIXI2_HOST: ${{ secrets.MIXI2_HOST }}
  MIXI2_STREAM_HOST: ${{ secrets.MIXI2_STREAM_HOST }}
  MIXI2_CLIENT_ID: ${{ secrets.MIXI2_CLIENT_ID }}
  MIXI2_CLIENT_SECRET: ${{ secrets.MIXI2_CLIENT_SECRET }}
  MIXI2_TOKEN_ENDPOINT: ${{ secrets.MIXI2_TOKEN_ENDPOINT }}
  MIXI2_AUTH_KEY: ${{ secrets.MIXI2_AUTH_KEY }}
  MIXI2_TEST_ROOM_ID: ${{ secrets.MIXI2_TEST_ROOM_ID }}

jobs:
  jvm-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run JVM tests
        shell: bash
        run: |
          ./gradlew core:jvmTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jvm-test-results-${{ matrix.os }}
          path: core/build/reports/tests/jvmTest/

  native-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            gradle-target: macosArm64Test
          - os: ubuntu-latest
            gradle-target: linuxX64Test
          - os: windows-latest
            gradle-target: mingwX64Test
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Native tests
        shell: bash
        run: |
          ./gradlew core:${{ matrix.gradle-target }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: native-test-results-${{ matrix.gradle-target }}
          path: core/build/reports/tests/${{ matrix.gradle-target }}/
